<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<packaging>pom</packaging>
	<modules>
		<module>casdoor-gateway</module>
		<module>casdoor-api</module>
	</modules>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.16</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>org.casbin</groupId>
	<artifactId>casdoor-spring-cloud-gateway-example</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>casdoor-spring-cloud-gateway-example</name>
	<description>Sign in with Casdoor in Spring Cloud Gateway</description>
	<properties>
		<java.version>17</java.version>
		<spring-cloud.version>2025.0.3</spring-cloud.version>
		<casdoor-spring-boot-starter.version>2.0.1</casdoor-spring-boot-starter.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.casbin</groupId>
				<artifactId>casdoor-spring-boot-starter</artifactId>
				<version>${casdoor-spring-boot-starter.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
